COMPANIES = [
    {"name": "Adani Enterprises", "ticker": "ADANIENT.NS", "sector": "Conglomerate"},
    {"name": "Adani Ports & SEZ", "ticker": "ADANIPORTS.NS", "sector": "Logistics"},
    {"name": "Apollo Hospitals", "ticker": "APOLLOHOSP.NS", "sector": "Healthcare"},
    {"name": "Asian Paints", "ticker": "ASIANPAINT.NS", "sector": "Consumer Goods"},
    {"name": "Axis Bank", "ticker": "AXISBANK.NS", "sector": "Banking"},
    {"name": "Bajaj Auto", "ticker": "BAJAJ-AUTO.NS", "sector": "Automobile"},
    {"name": "Bajaj Finance", "ticker": "BAJFINANCE.NS", "sector": "NBFC"},
    {"name": "Bajaj Finserv", "ticker": "BAJAJFINSV.NS", "sector": "Financial Services"},
    {"name": "Bharti Airtel", "ticker": "BHARTIARTL.NS", "sector": "Telecom"},
    {"name": "Britannia Industries", "ticker": "BRITANNIA.NS", "sector": "FMCG"},
    {"name": "Cipla", "ticker": "CIPLA.NS", "sector": "Pharmaceuticals"},
    {"name": "Coal India", "ticker": "COALINDIA.NS", "sector": "Mining"},
    {"name": "Divi's Laboratories", "ticker": "DIVISLAB.NS", "sector": "Pharmaceuticals"},
    {"name": "Dr. Reddy's Laboratories", "ticker": "DRREDDY.NS", "sector": "Pharmaceuticals"},
    {"name": "Eicher Motors", "ticker": "EICHERMOT.NS", "sector": "Automobile"},
    {"name": "Grasim Industries", "ticker": "GRASIM.NS", "sector": "Cement & Textiles"},
    {"name": "HCL Technologies", "ticker": "HCLTECH.NS", "sector": "IT Services"},
    {"name": "HDFC Bank", "ticker": "HDFCBANK.NS", "sector": "Banking"},
    {"name": "HDFC Life Insurance", "ticker": "HDFCLIFE.NS", "sector": "Insurance"},
    {"name": "Hero MotoCorp", "ticker": "HEROMOTOCO.NS", "sector": "Automobile"},
    {"name": "Hindalco Industries", "ticker": "HINDALCO.NS", "sector": "Metals"},
    {"name": "Hindustan Unilever", "ticker": "HINDUNILVR.NS", "sector": "FMCG"},
    {"name": "ICICI Bank", "ticker": "ICICIBANK.NS", "sector": "Banking"},
    {"name": "ITC", "ticker": "ITC.NS", "sector": "FMCG"},
    {"name": "IndusInd Bank", "ticker": "INDUSINDBK.NS", "sector": "Banking"},
    {"name": "Infosys", "ticker": "INFY.NS", "sector": "IT Services"},
    {"name": "JSW Steel", "ticker": "JSWSTEEL.NS", "sector": "Metals"},
    {"name": "Kotak Mahindra Bank", "ticker": "KOTAKBANK.NS", "sector": "Banking"},
    {"name": "LTIMindtree", "ticker": "LTIM.NS", "sector": "IT Services"},
    {"name": "Larsen & Toubro", "ticker": "LT.NS", "sector": "Infrastructure"},
    {"name": "Mahindra & Mahindra", "ticker": "M&M.NS", "sector": "Automobile"},
    {"name": "Maruti Suzuki", "ticker": "MARUTI.NS", "sector": "Automobile"},
    {"name": "Nestle India", "ticker": "NESTLEIND.NS", "sector": "FMCG"},
    {"name": "NTPC", "ticker": "NTPC.NS", "sector": "Power"},
    {"name": "Oil & Natural Gas Corporation", "ticker": "ONGC.NS", "sector": "Oil & Gas"},
    {"name": "Power Grid Corporation", "ticker": "POWERGRID.NS", "sector": "Power"},
    {"name": "Reliance Industries", "ticker": "RELIANCE.NS", "sector": "Conglomerate"},
    {"name": "SBI Life Insurance", "ticker": "SBILIFE.NS", "sector": "Insurance"},
    {"name": "State Bank of India", "ticker": "SBIN.NS", "sector": "Banking"},
    {"name": "Sun Pharma", "ticker": "SUNPHARMA.NS", "sector": "Pharmaceuticals"},
    {"name": "TCS", "ticker": "TCS.NS", "sector": "IT Services"},
    {"name": "Tata Consumer Products", "ticker": "TATACONSUM.NS", "sector": "FMCG"},
    {"name": "Tata Motors", "ticker": "TATAMOTORS.NS", "sector": "Automobile"},
    {"name": "Tata Steel", "ticker": "TATASTEEL.NS", "sector": "Metals"},
    {"name": "Tech Mahindra", "ticker": "TECHM.NS", "sector": "IT Services"},
    {"name": "Titan Company", "ticker": "TITAN.NS", "sector": "Consumer Goods"},
    {"name": "UltraTech Cement", "ticker": "ULTRACEMCO.NS", "sector": "Cement"},
    {"name": "Wipro", "ticker": "WIPRO.NS", "sector": "IT Services"},
]